title = "Adamw-lc2"
description = "Otimização utizando bacc, 200 epocas, 300 trials, 7 runs/trial."

[params]
hidden-neurons=13
dropout=0.20
lr=0.017
flood-penalty=0.32
soft-label-topline=0.57
soft-label-baseline=0.39
soft-label-baseline-slope=0.0
sched-steps=64
sched-gamma=0.18
eps=1e-06
lambda1-dim1=1e-08
lambda1-dim2=1e-08
lambda2-dim1=3e-12
lambda2-dim2=1e-08
wd=1e-10
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc2"

[run]
epochs=300
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-snps=false
shuffled-labels=false
shuffled-ages=false
shuffled-parents=false
families=false
