title = "Radam-lc1"
description = "Otimização utizando bacc, 500 epocas, 300 trials, 7 runs/trial"

[params]
hidden-neurons=18
dropout=0.07
lr=0.012
flood-penalty=0.08
soft-label-topline=1.0
soft-label-baseline=0.4
sched-steps=78
sched-gamma=0.09
eps=5e-07
lambda1-dim1=3e-07
lambda1-dim2=8e-09
lambda2-dim1=7e-06
lambda2-dim2=1e-12
wd=4e-09
beta1=0.9
beta2=0.999
batch-size=256
optimizer="radam"
lc-layer="lc1"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=true
negative=true
shuffled-positive=true
families=true
