title = "Radam-lc2"
description = "Otimização utizando fscore, 500 epocas, 300 trials, 7 runs/trial"

[params]
hidden-neurons=15
dropout=0.12
lr=0.006
flood-penalty=0.27
soft-label-topline=0.95
soft-label-baseline=0.35
sched-steps=120
sched-gamma=0.3
eps=0.0026
lambda1-dim1=1e-05
lambda1-dim2=1e-05
lambda2-dim1=1e-05
lambda2-dim2=1e-05
wd=1e-05
beta1=0.9
beta2=0.999
batch-size=256
optimizer="radam"
lc-layer="lc2"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=true
negative=true
shuffled-positive=true
families=true
