title = "Adamw-lc4"
description = "Otimização utizando bacc, 200 epocas, 300 trials, 7 runs/trial."

[params]
hidden-neurons=13
dropout=0.30
lr=0.005
flood-penalty=0.0
soft-label-topline=0.87
soft-label-baseline=0.30
soft-label-baseline-slope=-0.45
sched-steps=103
sched-gamma=0.61
eps=5e-06
lambda1-dim1=1e-11
lambda1-dim2=2e-10
lambda2-dim1=7e-10
lambda2-dim2=4e-07
wd=8e-10
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc4"

[run]
epochs=300
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-snps=false
shuffled-labels=false
shuffled-ages=false
shuffled-parents=false
families=false
