title = "Adamw-lc4"
description = "Otimização utizando bacc, 500 epocas, 300 trials, 7 runs/trial"

[params]
hidden-neurons=8
dropout=0.00
lr=0.012
flood-penalty=0.00
soft-label-topline=0.66
soft-label-baseline=0.19
sched-steps=22
sched-gamma=0.05
eps=2e-07
lambda1-dim1=41e-08
lambda1-dim2=3e-10
lambda2-dim1=2e-07
lambda2-dim2=2e-05
wd=1e-11
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc4"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=true
negative=true
shuffled-positive=true
families=true

