title = "Adamw-lc2"
description = "Otimização utizando bacc, 500 epocas, 300 trials, 7 runs/trial. TESTE DA ALTERACAO TANH->SIGMOID"


[params]
hidden-neurons=5
dropout=0.06
lr=0.005
flood-penalty=0.38
soft-label-topline=1.0
soft-label-baseline=0.48
sched-steps=96
sched-gamma=0.09
eps=2e-07
lambda1-dim1=4e-10
lambda1-dim2=3e-06
lambda2-dim1=1e-05
lambda2-dim2=1e-06
wd=3e-07
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc2"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-positive=false
families=false

