title = "Teste de uma rede neural"
description = ""

[params]
hidden-neurons=15
dropout=0.15
lr=0.1
eps=1e-05
wd=1e-08
lambda1-dim1=1e-06
lambda2-dim1=1e-06
lambda1-dim2=1e-08
lambda2-dim2=1e-09
flood-penalty=0.10
soft-label-topline=0.9
soft-label-baseline=0.3
sched-steps=90
sched-gamma=0.8
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc1"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=true
negative=true
shuffled-positive=true
families=true
