title = "Adamw-lc1"
description = "Otimização utizando bacc, 200 epocas, 300 trials, 7 runs/trial."

[params]
hidden-neurons=13
dropout=0.20
lr=0.006
flood-penalty=0.39
soft-label-topline=0.67
soft-label-baseline=0.46
soft-label-baseline-slope=-0.3
sched-steps=82
sched-gamma=0.66
eps=2e-06
lambda1-dim1=3e-08
lambda1-dim2=8e-07
lambda2-dim1=8e-10
lambda2-dim2=1e-07
wd=0.0
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc1"

[run]
epochs=300
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-snps=false
shuffled-labels=false
shuffled-ages=false
shuffled-parents=false
families=false

