title = "Adamw-lc2"
description = "Otimização utizando bacc, 500 epocas, 300 trials, 7 runs/trial"

[params]
hidden-neurons=3
dropout=0.05
lr=0.002
flood-penalty=0.08
soft-label-topline=1.0
soft-label-baseline=0.40
sched-steps=120
sched-gamma=0.2
eps=2e-08
lambda1-dim1=1e-11
lambda1-dim2=1e-08
lambda2-dim1=0.00033
lambda2-dim2=0.001
wd=1e-07
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc2"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=true
negative=true
shuffled-positive=true
families=true

