title = "Radam-lc2"
description = "Otimização utizando avg_prec, 500 epocas, 200 trials, 7 runs/trial"

[params]
hidden-neurons=17
dropout=0.42
lr=0.02
flood-penalty=0.17
soft-label-topline=0.85
soft-label-baseline=0.17
sched-steps=72
sched-gamma=0.39
eps=3e-08
lambda1-dim1=5e-06
lambda1-dim2=1e-12
lambda2-dim1=3e-05
lambda2-dim2=5e-07
wd=5e-10
beta1=0.9
beta2=0.999
batch-size=256
optimizer="radam"
lc-layer="lc2"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-positive=false
families=false
