title = "Adamw-lc3"
description = "Otimização utizando bacc, 200 epocas, 300 trials, 7 runs/trial."

[params]
hidden-neurons=13
dropout=0.0
lr=0.01
flood-penalty=0.19
soft-label-topline=0.58
soft-label-baseline=0.42
soft-label-baseline-slope=-0.29
sched-steps=55
sched-gamma=0.52
eps=2e-07
lambda1-dim1=1e-09
lambda1-dim2=2e-09
lambda2-dim1=6e-10
lambda2-dim2=1e-09
wd=0.0001
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc3"

[run]
epochs=300
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-snps=false
shuffled-labels=false
shuffled-ages=false
shuffled-parents=false
families=false
