title = "Adamw-lc1"
description = "Otimização utizando bacc, 500 epocas, 300 trials, 7 runs/trial. TESTE DA ALTERACAO TANH->SIGMOID e Softplus -> GELU"


[params]
hidden-neurons=9
dropout=0.03
lr=0.003
flood-penalty=0.24
soft-label-topline=1.0
soft-label-baseline=0.45
sched-steps=50
sched-gamma=0.37
eps=1e-08
lambda1-dim1=1e-09
lambda1-dim2=1e-06
lambda2-dim1=4e-09
lambda2-dim2=9e-09
wd=7e-10
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc1"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-positive=false
families=false

