title = "Radam-lc2"
description = "Otimização utizando f2-score, 500 epocas, 200 trials, 7 runs/trial"

[params]
hidden-neurons=9
dropout=0.07
lr=0.007
flood-penalty=0.44
soft-label-topline=0.84
soft-label-baseline=0.15
sched-steps=49
sched-gamma=0.31
eps=6e-08
lambda1-dim1=6e-08
lambda1-dim2=4e-05
lambda2-dim1=3e-10
lambda2-dim2=0.001
wd=8e-07
beta1=0.9
beta2=0.999
batch-size=256
optimizer="radam"
lc-layer="lc2"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-positive=false
families=false
