title = "Adamw-lc3"
description = "Otimização utizando bacc, 500 epocas, 300 trials, 7 runs/trial. TESTE DA ALTERACAO TANH->SIGMOID e Softplus -> GELU"


[params]
hidden-neurons=7
dropout=0.08
lr=0.01
flood-penalty=0.4
soft-label-topline=1.0
soft-label-baseline=0.3
soft-label-baseline-slope=-0.1
sched-steps=105
sched-gamma=0.5
eps=8e-08
lambda1-dim1=4e-08
lambda1-dim2=5e-05
lambda2-dim1=1e-09
lambda2-dim2=2e-06
wd=3e-08
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc5"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-positive=false
families=false

