title = "Adamw-lc1"
description = "Otimização utizando bacc, 500 epocas, 300 trials, 7 runs/trial"

[params]
hidden-neurons=13
dropout=0.03
lr=0.003
flood-penalty=0.38
soft-label-topline=1.0
soft-label-baseline=0.32
sched-steps=65
sched-gamma=0.05
eps=3e-07
lambda1-dim1=3e-10
lambda1-dim2=5e-07
lambda2-dim1=1e-08
lambda2-dim2=1e-06
wd=9e-08
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc1"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=true
negative=true
shuffled-positive=true
families=true

