title = "Radam-lc2"
description = "Otimização utizando bacc, 500 epocas, 300 trials, 7 runs/trial"

[params]
hidden-neurons=3
dropout=0.19
lr=0.004
flood-penalty=0.33
soft-label-topline=0.79
soft-label-baseline=0.13
sched-steps=132
sched-gamma=0.57
eps=1e-08
lambda1-dim1=3e-11
lambda1-dim2=1e-12
lambda2-dim1=9e-09
lambda2-dim2=4e-06
wd=2e-05
beta1=0.9
beta2=0.999
batch-size=256
optimizer="radam"
lc-layer="lc2"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=true
negative=true
shuffled-positive=true
families=true
