title = "Adamw-lc6"
description = "Otimização utizando bacc, 200 epocas, 300 trials, 7 runs/trial."

[params]
hidden-neurons=13
dropout=0.27
lr=0.008
flood-penalty=0.29
soft-label-topline=0.72
soft-label-baseline=0.35
soft-label-baseline-slope=-0.48
sched-steps=45
sched-gamma=0.56
eps=6e-06
lambda1-dim1=4e-10
lambda1-dim2=8e-06
lambda2-dim1=1e-08
lambda2-dim2=6e-07
wd=2e-07
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc6"

[run]
epochs=300
ensemble=100

[datasets]
positive=false
random=true
negative=true
shuffled-snps=true
shuffled-labels=true
shuffled-ages=true
shuffled-parents=true
families=true
