title = "Adamw-l6"
description = "Otimização utizando bacc, 500 epocas, 300 trials, 7 runs/trial"

[params]
hidden-neurons=3
dropout=0.14
lr=0.002
flood-penalty=0.29
soft-label-topline=1.0
soft-label-baseline=0.17
sched-steps=106
sched-gamma=0.31
eps=6e-06
lambda1-dim1=2e-10
lambda1-dim2=3e-06
lambda2-dim1=4e-07
lambda2-dim2=1e-05
wd=6e-07
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc6"

[run]
epochs=500
ensemble=100

[datasets]
positive=true
random=true
negative=true
shuffled-positive=true
families=true

