title = "Adamw-lc2-without-lambdas"
description = "Otimização MOO bacc e brier, 200 epocas, 500 trials, 7 runs/trial."

[params]
hidden-neurons=15
dropout=0.55
lr=0.01
flood-penalty=0.57
soft-label-topline=0.51
soft-label-baseline=0.49
soft-label-baseline-slope=-0.00345
sched-steps=105
sched-gamma=0.777
eps=1e-07
lambda1-dim1=0.0
lambda1-dim2=0.0
lambda2-dim1=0.0
lambda2-dim2=0.0
wd=4e-09
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc2"

[run]
epochs=300
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-snps=false
shuffled-labels=false
shuffled-ages=false
shuffled-parents=false
families=false
