title = "Adamw-lc3-without-dropout"
description = "Otimização MOO bacc e brier, 200 epocas, 500 trials, 7 runs/trial."

[params]
hidden-neurons=11
dropout=0.0
lr=0.017
flood-penalty=0.61
soft-label-topline=0.51
soft-label-baseline=0.49
soft-label-baseline-slope=-0.0032
sched-steps=120
sched-gamma=0.55
eps=1e-08
lambda1-dim1=9e-10
lambda1-dim2=1e-12
lambda2-dim1=5e-09
lambda2-dim2=1e-10
wd=1e-06
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc3"

[run]
epochs=300
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-snps=false
shuffled-labels=false
shuffled-ages=false
shuffled-parents=false
families=false

