title = "Adamw-lc5-without-dropout"
description = "Otimização MOO bacc e brier, 200 epocas, 500 trials, 7 runs/trial."

[params]
hidden-neurons=7
dropout=0.0
lr=0.022
flood-penalty=0.0
soft-label-topline=0.51
soft-label-baseline=0.40
soft-label-baseline-slope=-0.0033
sched-steps=95
sched-gamma=0.999999
eps=1e-08
lambda1-dim1=2e-10
lambda1-dim2=4e-08
lambda2-dim1=4e-06
lambda2-dim2=8e-07
wd=1e-12
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc5"

[run]
epochs=300
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-snps=false
shuffled-labels=false
shuffled-ages=false
shuffled-parents=false
families=false

