title = "Adamw-lc7-without-lambdas"
description = "Otimização MOO bacc e brier, 200 epocas, 500 trials, 7 runs/trial."

[params]
hidden-neurons=21
dropout=0.57
lr=0.01
flood-penalty=0.32
soft-label-topline=0.51
soft-label-baseline=0.49
soft-label-baseline-slope=-0.0040
sched-steps=110
sched-gamma=0.05
eps=1e-07
lambda1-dim1=0.0
lambda1-dim2=0.0
lambda2-dim1=0.0
lambda2-dim2=0.0
wd=0.01
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc7"

[run]
epochs=300
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-snps=false
shuffled-labels=false
shuffled-ages=false
shuffled-parents=false
families=false

