title = "Adamw-lc1-without-lambdas"
description = "Otimização MOO bacc e brier, 200 epocas, 500 trials, 7 runs/trial."

[params]
hidden-neurons=8
dropout=0.6
lr=0.015
flood-penalty=0.39
soft-label-topline=0.51
soft-label-baseline=0.49
soft-label-baseline-slope=-0.0035
sched-steps=150
sched-gamma=0.999
eps=1e-08
lambda1-dim1=0.0
lambda1-dim2=0.0
lambda2-dim1=0.0
lambda2-dim2=0.0
wd=1e-12
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc1"

[run]
epochs=300
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-snps=false
shuffled-labels=false
shuffled-ages=false
shuffled-parents=false
families=false


