title = "Adamw-lc4-without-flood-penalty"
description = "Otimização MOO bacc e brier, 200 epocas, 500 trials, 7 runs/trial."

[params]
hidden-neurons=17
dropout=0.24
lr=0.019
flood-penalty=0.0
soft-label-topline=0.51
soft-label-baseline=0.49
soft-label-baseline-slope=-0.004
sched-steps=52
sched-gamma=0.73
eps=3e-08
lambda1-dim1=2e-08
lambda1-dim2=2e-10
lambda2-dim1=0.00065
lambda2-dim2=1e-12
wd=1e-07
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc4"

[run]
epochs=300
ensemble=100

[datasets]
positive=true
random=false
negative=false
shuffled-snps=false
shuffled-labels=false
shuffled-ages=false
shuffled-parents=false
families=false
