title = "Full Training Procedure for DiabNet"
# Train DiabNet with all available datasets

[params]
hidden-neurons=13
dropout=0.27
lr=0.035
flood-penalty=0.48
soft-label-topline=0.73
soft-label-baseline=0.44
soft-label-baseline-slope=-0.56
sched-steps=49
sched-gamma=0.65
eps=1e-05
lambda1-dim1=4e-08
lambda1-dim2=7e-08
lambda2-dim1=1e-10
lambda2-dim2=3e-07
wd=1e-12
beta1=0.9
beta2=0.999
batch-size=256
optimizer="adamw"
lc-layer="lc5"

[run]
epochs=300
ensemble=100

[datasets]
positive=true
random=true
negative=true
shuffled-snps=true
shuffled-labels=true
shuffled-ages=true
shuffled-parents=true
families=true
